### ISSUE TITLE
提议 timeout reset 开放出来在外部也可以调用

### ISSUE THREAD

**Issue by kerwin-cn** [AspenLuoQiang/hyoga-uni-socket.io#17]
timeout reset那个函数开放一下啊，外部能够调用 不是socket.io. ping pang 的就不是很好 用

**Comment by guyue88** [comment]
> timeout reset那个函数开放一下啊，外部能够调用 不是socket.io. ping pang 的就不是很好 用

@kerwin-cn 你说的是  resetPingTimeout 方法？这个本身就在socket对象上面，你可以直接调用的
