### ISSUE TITLE
Hbuilder2.7.5版本下，报SyntaxError: Unexpected token '...'. Expected a property name 错误

### ISSUE THREAD

**Issue by hy353** [AspenLuoQiang/hyoga-uni-socket.io#2]
在最新的2.7.5版本下报SyntaxError: Unexpected token '...'. Expected a property name.错误。
通过查阅源代码。
this._socket=function(t){const e=a.connectSocket({complete:()=>{},...t});
错误出现在这行代码的扩展运算符。删除即可解决

**Comment by guyue88** [comment]
您好，这块代码是发起链接的地方，肯定不能删除。
我刚实验了一下，没有出现报错，能否提供一个demo代码给我看看？
![image](https://user-images.githubusercontent.com/12598256/82413609-3c980380-9aa8-11ea-91d9-880179b7ebd9.png)

**Comment by hy353** [comment]
我同时使用了laravel-echo。
所以，不是直接使用的标准调用代码。
![微信截图_20200521180110](https://user-images.githubusercontent.com/64407319/82547928-1304d800-9b8d-11ea-9c07-784e47945c5c.png)

**Comment by guyue88** [comment]
@hy353 你是通过这个库来调用的 hyoga-uni-socket.io 吗？直接使用 hyoga-uni-socket.io 会不会报错呢？

**Comment by hy353** [comment]
我直接使用 hyoga-uni-socket.io ，依然报错
![微信图片_20200523132944](https://user-images.githubusercontent.com/64407319/82722452-7e6bb880-9cf9-11ea-8b9b-a61619d524da.png)

**Comment by hy353** [comment]
![微信截图_20200523133027](https://user-images.githubusercontent.com/64407319/82722460-
95120f80-9cf9-11ea-89f2-08a8363bae66.png)
而且真机运行时，无法连接到websocket

**Comment by hy353** [comment]
![微信截图_20200523133027](https://user-images.githubusercontent.com/64407319/82722467-ab1fd000-9cf9-11ea-9dd6-46078232ccc2.png)
真机运行时，无法连接到websocket

**Comment by guyue88** [comment]
@hy353 能不能提供一个小示例，这样子的我没办法猜出问题在哪！！

**Comment by hy353** [comment]
let socket = io("wss://jslapi.dskchain.net", {
    path: "/ws/socket.io",
    query: { EIO: 3, transport: "websocket" },
    transports: ["websocket", "polling"],
    timeout: 5000
  });
  socket.emit("subscribe", { channel: "jsl-publish", auth: { headers: {} } });
  socket.on("jsl.product", (channel, e) => {
   console.log(e);
  });

**Comment by callmez** [comment]
@AspenLuoQiang 应该是uniapp不会转译node_modules的es6语法问题

你可以试着把webpack编译选项转译到es5语法.

**Comment by guyue88** [comment]
@callmez npm 包暴露的是编译的文件，不包含es6语法的，所以我让 @hy353 提供一个示例才能看看问题出在哪

**Comment by hy353** [comment]
![微信截图_20200523145114](https://user-images.githubusercontent.com/64407319/82723918-de1b9100-9d04-11ea-8c1a-9fa11954cf3e.png)
这是格式化后的代码。 `...t`是ES6语法 @AspenLuoQiang

**Comment by guyue88** [comment]
@hy353是不是ES6的问题，只是猜测，你抽个demo出来，我来看看是不是这里的问题，我之前自己弄的demo确实没有报错！！不提供demo我无法靠猜测解决问题！！！！

**Comment by hy353** [comment]
@AspenLuoQiang  我直接把dist抽出来用了。可以用了。就这样吧。
