### ISSUE TITLE
ArrayBuffer报错

### ISSUE THREAD

**Issue by cryptopeng** [AspenLuoQiang/hyoga-uni-socket.io#4]
uni-socket.io链接报错：

    import io from "@/js_sdk/hyoga-uni-socket_io/uni-socket.io.js"
    export default {
    	data() {
    		return {
    		}
    	},
    	mounted() {
    		console.log("Socket page mounted!")
    		var socket = io(`ws://dev.ws.klinepusher.bandex.lvyii.com:18843`, {
    		  path: '/kline.pusher',
    		  transports: ['websocket', 'polling'],
    		  query: {
    		    token: ""
    		  },
    		})
    	},
    	methods: {
    	}
    }

报错信息：

10:47:02.378 [ERROR] : [Vue warn]: Error in event handler for "api.onSocketTaskStateChange": "Error: Unknown type: [object ArrayBuffer]"
10:47:02.378 (found <Root>) ERROR 
10:47:02.403 [ERROR] : Error: Unknown type: [object ArrayBuffer] ERROR 

uni-app websocket api正常示例

    	import io from "@/js_sdk/hyoga-uni-socket_io/uni-socket.io.js"
    	export default {
    		data() {
    			return {
    			}
    		},
    		mounted() {
    			console.log("Socket page mounted!")
    			var socketTask = uni.connectSocket({
    			    url: 'ws://dev.ws.klinepusher.bandex.lvyii.com:18843/kline.pusher/?token=&EIO=3&transport=websocket',
    			    complete: ()=> {
    					console.log("socket connect success!")
    				}
    			});
    		},
    		methods: {
    		}
    	}

控制台打印：

10:51:02.969 正在重启，如手机上HBuilder调试基座未启动，请手动启动...
10:51:04.256 [LOG] : App Launch at App.vue:4 
10:51:04.277 [LOG] : App Show at App.vue:7 
10:51:05.255 [LOG] : Socket page mounted! at pages/socket/index.vue:15 
10:51:05.277 [LOG] : socket connect success! at pages/socket/index.vue:26

**Comment by hudongya** [comment]
> uni-socket.io链接报错：
> 
> ```
> import io from "@/js_sdk/hyoga-uni-socket_io/uni-socket.io.js"
> export default {
> 	data() {
> 		return {
> 		}
> 	},
> 	mounted() {
> 		console.log("Socket page mounted!")
> 		var socket = io(`ws://dev.ws.klinepusher.bandex.lvyii.com:18843`, {
> 		  path: '/kline.pusher',
> 		  transports: ['websocket', 'polling'],
> 		  query: {
> 		    token: ""
> 		  },
> 		})
> 	},
> 	methods: {
> 	}
> }
> ```
> 
> 报错信息：
> 
> 10:47:02.378 [ERROR] : [Vue warn]: Error in event handler for "api.onSocketTaskStateChange": "Error: Unknown type: [object ArrayBuffer]"
> 10:47:02.378 (found ) ERROR
> 10:47:02.403 [ERROR] : Error: Unknown type: [object ArrayBuffer] ERROR
> 
> uni-app websocket api正常示例
> 
> ```
> 	import io from "@/js_sdk/hyoga-uni-socket_io/uni-socket.io.js"
> 	export default {
> 		data() {
> 			return {
> 			}
> 		},
> 		mounted() {
> 			console.log("Socket page mounted!")
> 			var socketTask = uni.connectSocket({
> 			    url: 'ws://dev.ws.klinepusher.bandex.lvyii.com:18843/kline.pusher/?token=&EIO=3&transport=websocket',
> 			    complete: ()=> {
> 					console.log("socket connect success!")
> 				}
> 			});
> 		},
> 		methods: {
> 		}
> 	}
> ```
> 
> 控制台打印：
> 
> 10:51:02.969 正在重启，如手机上HBuilder调试基座未启动，请手动启动...
> 10:51:04.256 [LOG] : App Launch at App.vue:4
> 10:51:04.277 [LOG] : App Show at App.vue:7
> 10:51:05.255 [LOG] : Socket page mounted! at pages/socket/index.vue:15
> 10:51:05.277 [LOG] : socket connect success! at pages/socket/index.vue:26

请问问题解决了吗？？？

**Comment by guyue88** [comment]
ArrayBuffer问题是uniapp websocket的bug，官方已经修复过了

**Comment by yybetta** [comment]
> ArrayBuffer问题是uniapp websocket的bug，官方已经修复过了

我使用的是uni-socket.io1.0.1 服务端用的是2.X的版本，HBuilderX 3.2.12 目前也是连接ok，接收二进制消息报这个错， [Vue warn]: Error in event handler for "api.onSocketTaskStateChange": "Error: Unknown type: [object ArrayBuffer]"
16:38:21.102 (found <Root>) __ERROR 
16:38:21.123  Error: Unknown type: [object ArrayBuffer] __ERROR ， 请问是怎么回事啊

**Comment by guyue88** [comment]
@yybetta 能否提供完整例子，我定位看一下

**Comment by yybetta** [comment]
> @yybetta 能否提供完整例子，我定位看一下

好的，已发邮件 lq9328@126.com 谢谢;
